### ISSUE TITLE
[error-rubocop] can't modify frozen String

### ISSUE THREAD

**Issue by hnegishi** [hnegishi/rails-board#5]
## 内容

commit時にrubocopでエラー
```
Analyze with RuboCop........................................[RuboCop] FAILED
Hook raised unexpected error
can't modify frozen String
/Users/hnegishi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/overcommit-0.47.0/lib/overcommit/hook/base.rb:209:in `check_for_executable'
/Users/hnegishi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/overcommit-0.47.0/lib/overcommit/hook/base.rb:199:in `check_for_requirements'
/Users/hnegishi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/overcommit-0.47.0/lib/overcommit/hook/base.rb:44:in `run_and_transform'
/Users/hnegishi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/overcommit-0.47.0/lib/overcommit/hook_runner.rb:164:in `run_hook'
/Users/hnegishi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/overcommit-0.47.0/lib/overcommit/hook_runner.rb:97:in `block in consume'
/Users/hnegishi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/overcommit-0.47.0/lib/overcommit/hook_runner.rb:94:in `loop'
/Users/hnegishi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/overcommit-0.47.0/lib/overcommit/hook_runner.rb:94:in `consume'
```

frozen_string_literal: trueで文字列リテラルはすべてfreezeされた状態になっているにも関わらず
変更されているためエラーになっている。

## 疑問点
- Rubocopでなぜovercommit(プロジェクト外のパス)で引っかかってる？

**Comment by hnegishi** [comment]
とりあえず、`/Users/hnegishi/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/gems/overcommit-0.47.0/lib/overcommit/hook/base.rb`を確認。
```
- # frozen_string_literal: true
+ # frozen_string_literal: false
```
に変更してみて再度commitして様子見てみる

```
Analyze with RuboCop........................................[RuboCop] FAILED
'rubocop' is not installed, not in your PATH, or does not have execute permissions
Install it by running: gem install rubocop
```

Rubocopが入ってない事になってる。なぜ...？
`# frozen_string_literal: false`にした事で文字リテラルが変更されてRubocopを参照している部分が途切れたから？

ひとまず、再インストール
```
gem install rubocop
```
これでcommitしてみたら通った。
すごく納得行かないけど。
